# Generated by Django 4.1.7 on 2023-05-18 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='activation_sent',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_active',
        ),
    ]
